server:
  port: ${PORT:${SERVER_PORT:0}}
  servlet:
    context-path: /canchas/

idRandom: ${random.value}

spring:
  datasource:
    url: jdbc:mysql://db.ctd.academy:3306/pi21023c02_GRUPO1
    driverClassName: com.mysql.cj.jdbc.Driver
    username: pi21023c02_GRUPO1
    password: Eeth9kai
#    url: jdbc:mysql://localhost:3306/canchalibre
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: cancha-libre
  mail:
    host: smtp.gmail.com
    port: 587
    username: canchalibreapp@gmail.com
    password: ohfhikwgnqdhzrxm
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
#eureka:
#  instance:
#    hostname: localhost
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    registerWithEureka: true
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
eureka:
  instance:
    hostname:  ec2-54-174-87-60.compute-1.amazonaws.com
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http:// ec2-54-174-87-60.compute-1.amazonaws.com:8761/eureka/
