server:
  port: ${PORT:${SERVER_PORT:0}}

idRandom: ${random.value}

spring:
  datasource:
    url: jdbc:mysql://db.ctd.academy:3306/pi21023c02_GRUPO1
    driverClassName: com.mysql.cj.jdbc.Driver
    username: pi21023c02_GRUPO1
    password: Eeth9kai
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-autocreate: update
  application:
    name: cancha-libre
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
