server:
  port: 8080
  cloud:
    gateway:
      routes:
        - id: productRoute
          uri: http://localhost:8081
          predicates:
            - Path=
spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/