name: Build & Deploy Back End

on:
  push:
    branches: ["main"]
    paths:
      - '/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'Gateway/**'

jobs:
  config-aws:
    name: Config AWS credentials
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

  deploy-user:
    needs: config-aws
    name: Build User with Maven
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Configure SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY_USER }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEPLOY_SERVER_IP_USER }} >> ~/.ssh/known_hosts
      env:
        HOST: ${{ secrets.DEPLOY_SERVER_IP_USER }}

    - name: Build & Deploy discovery
      run: |
        echo "Building app..."
        cd discovery
        mvn install --file pom.xml
        echo "Finished building the app."
        
        
    - name: Build Gateway
      run: |
        echo "Building app..."
        cd Gateway
        mvn install --file pom.xml
        echo "Finished building the app."

    - name: Build cancha-libre
      run: |
        echo "Building app..."
        cd cancha-libre
        mvn install --file pom.xml
        echo "Finished building the app."

    - name: Deploy discovery
      run: |
        echo "Deploying started..."
        #ssh ubuntu@${HOST} sudo systemctl stop user.service
        scp /home/runner/work/proyecto_integrador_2_g1/discovery/target/discovery.jar ubuntu@${HOST}:~/user
        ssh ubuntu@${HOST} sudo systemctl start user.service
        echo "Finished deploying the app."
      env:
          HOST: ${{ secrets.DEPLOY_SERVER_IP_USER }}       
        
    - name: Deploy Gateway
      run: |
        echo "Deploying started..."
        #ssh ubuntu@${HOST} sudo systemctl stop user.service
        scp /home/runner/work/proyecto_integrador_2_g1/Gateway/target/Gateway.jar ubuntu@${HOST}:~/user
        ssh ubuntu@${HOST} sudo systemctl start user.service
        echo "Finished deploying the app."
      env:
          HOST: ${{ secrets.DEPLOY_SERVER_IP_USER }}

    - name: Deploy cancha-libre
      run: |
        echo "Deploying started..."
        #ssh ubuntu@${HOST} sudo systemctl stop user.service
        scp /home/runner/work/proyecto_integrador_2_g1/cancha-libre/target/cancha-libre.jar ubuntu@${HOST}:~/user
        ssh ubuntu@${HOST} sudo systemctl start user.service
        echo "Finished deploying the app."
      env:
          HOST: ${{ secrets.DEPLOY_SERVER_IP_USER }}    

          

